### ISSUE TITLE
Why is this message duplicated within the for loop?

### ISSUE THREAD

**Issue by gempa-jabe** [swiss-seismological-service/sed-SeisComP-contributions#19]
https://github.com/swiss-seismological-service/sed-SeisComP-contributions/blob/6014f671a85ad4a69d3b3380e1abfcabf10c9d17/apps/screloc/main.cpp#L285

**Comment by luca-s** [comment]
The line 285 is the only one I would like to see printed and it is useful when relocating many origins, to give a feedback to the user on the processing time. 

However, it is useful to print also the same line at 288 otherwise the user would think that not all origins were processed. 

Would you prefer to change it?

**Comment by gempa-jabe** [comment]
No, I am just asking. So if you process 100 origins then you will get the message twice. Fine with me.

**Comment by luca-s** [comment]
Yes, I know that it is not a very elegant, but it serves the purpose. I am willing to improve it in case, just let me know.
